language: shell
os: linux
arch: amd64
dist: bionic

services: docker

branches:
  only:
    - master

env:
  - PYTHON_VERSION=2.7.17

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --pull -t alvisisme/python:$PYTHON_VERSION -f $PYTHON_VERSION/Dockerfile $PYTHON_VERSION
  - docker push alvisisme/python:$PYTHON_VERSION
